version: "3.9"
services:
  ocr-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ocr-app:latest
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      STREAMLIT_SERVER_HEADLESS: "true"
    restart: unless-stopped
